manifest : "/Users/xaviguitart/Desktop/school_related/University_Of_Washington/phd/software/in_development/20220718_smk_get_annotate_locus/manifest.txt"
locus_fa :  "/net/eichler/vol26/projects/SD_Gene_Fam/nobackups/orthology_analysis/TBC1D3/in_progress/20220718_verkko_validate_compare/hg38_TBC1D3L.fa"
